### ISSUE TITLE
Enquiry of Comsol generated data

### ISSUE THREAD

**Issue by biteteemo** [TaghizadehE/explicit-PINN#1]
Hi, EhsanTaghizadeh,

Could you add the generated Comsol data to the data file? I got one error when I run the run.py file.

FileNotFoundError: [Errno 2] No such file or directory: 'data\\Comsol_output_Pe_u_Brinkman__Phi2_III__R8192_1.csv'

Thank you so much.

Xu Zo
![1648538412(1)](https://user-images.githubusercontent.com/71021228/160555951-408f0639-943f-491b-8b3e-9358eed1a6b2.jpg)

**Comment by TaghizadehE** [comment]
Hi Xu,

I uploaded the missing file.


Thank you,
